export const url = "http://127.0.0.1:3000/"
export const pageMap = {
  "/": ["home-btn", 55],
  "/home": ["home-btn", 55],
  "/signin": ["authentication-in-btn", 145],
  "/signup": ["authentication-up-btn", 235],
  "/register": ["registration-btn", 325],
  "/dashboard": ["dashboard"],
  "/marketplace": ["marketplace"],
  "/stripe-payment": ["stripe-payment-page-add"],
  "/stripe-payout": ["stripe-payment-page-withdraw"],
  "/payment-success/": ["stripe-payment-success-page"]
};
export const getCorrectDataMap = {
  certifying_bodies_for_ui: {
    W: "WREGIS",
    P: "PJM",
    E: "ERCOT",
    MI: "MIRECS",
    MR: "M-RETS",
    N: "NAR",
    NC: "NC-RETS",
    NE: "NEPOLL-GI",
    NV: "NVREK",
    NY: "NYGATS",
    NON: "NONE",
  },
  certifying_body: {
    W: "WREGIS",
    P: "PJM",
    E: "ERCOT",
    MI: "MIRECS",
    MR: "M-RETS",
    N: "NAR",
    NC: "NC-RETS",
    NE: "NEPOLL-GI",
    NV: "NVREK",
    NY: "NYGATS",
    NON: "NONE",
  },
  generator_type: {
    S: "SOLAR",
    W: "WIND",
    H: "HYDRO",
    G: "GEO",
    BM: "BIOMASS",
    BG: "BIOGAS",
    V: "VAR",
  },
  status: {
    MRR: "MINT_REVIEW_REQ",
    MR: "MINT_REQ",
    M: "MINTED",
    RRR: "RETIRE_REVIEW_REQ",
    RR: "RETIRE_REQ",
    R: "RETIRED",
    WRR: "WITHDRAW_REVIEW_REQ",
    WR: "WITHDRAW_REQ",
    W: "WITHDRAWN",
    TR: "TRANSFER_REQ",
    T: "TRANSFERRED",
    S: "SUSPENDED",

    D: "DRAFT",
    SR: "SUBMIT_REQ",
    AC: "ACCEPTED",
    CR: "CANCEL_REQ",
    C: "CANCELLED",
    FR: "FILL_REQ",
    F: "FILLED",
    EX: "EXPIRED",
  },
  order_type: {
    A: "AUCTION",
    M: "MARKET",
  },
  side: {
    S: "SELL",
    B: "BUY",
  },
  tx_type: {
    M: "MINT",
    R: "RETIRE",
    W: "WITHDRAW",
    TR: "TRANSFER",
    TX: "TRADE",
  },
};
export const marketPlaceReverseMap = {
  "generator_type": {
    S: "SOLAR",
    W: "WIND",
    H: "HYDRO",
    G: "GEO",
    BM: "BIOMASS",
    BG: "BIOGAS",
    V: "VAR",
  },
  "entity_type": {
    P: "FOR PROFIT",
    N: "NON PROFIT",
  },
  "certifying_body": {
    W: "WREGIS",
    P: "PJM",
    E: "ERCOT",
    MI: "MIRECS",
    MR: "M-RETS",
    N: "NAR",
    NC: "NC-RETS",
    NE: "NEPOLL-GI",
    NV: "NVREK",
    NY: "NYGATS",
    NON: "NONE",
  }
};
export const marketplaceFiltermap = [
  ["generator_types", "Generator Type", "generator"],
  ["states", "States", "states"],
  ["certifying_bodies", "Certifying Body", "certifying"],
  ["qty", "Quantity", "quantity"],
  ["side", "Order Side", "side"],
]

export const marketPlaceMap = {
  changeGenerator: [],
  changeOwner: [""],
  action: [
    ["Remove", "withdraw"],
    ["Retire", "retire"],
    ["Transfer", "transfer"],
  ],
  entity_type: [
    ["FOR PROFIT", "P"],
    ["NON PROFIT", "N"],
  ],
  alreadyListedGenerator: [],

  generator_type: [
    ["GEOTHERMAL", "G"],
    ["SOLAR", "S"],
    ["WIND", "W"],
    ["HYDRO", "H"],
    ["BIOMASS", "B"],
    ["BIOGAS", "B"],
    ["VARIOUS", "V"],
  ],
  generator_types: [
    ["GEOTHERMAL", "G"],
    ["SOLAR", "S"],
    ["WIND", "W"],
    ["HYDRO", "H"],
    ["BIOMASS", "B"],
    ["BIOGAS", "B"],
    ["VARIOUS", "V"],
  ],
  customerClass: [],
  certifying_bodies: [
    ["WREGIS", "W"],
    ["PJM_GATS", "P"],
    ["ERCOT", "E"],
    ["MIRECS", "MI"],
    ["M_RETS", "MR"],
    ["NAR", "N"],
    ["NC_RETS", "NC"],
    ["NEPOOL_GIS", "NE"],
    ["NVTREK", "NV"],
    ["NYGATS", "NY"],
    ["NONE", "NON"],
  ],
  certifying_body: [
    ["WREGIS", "W"],
    ["PJM_GATS", "P"],
    ["ERCOT", "E"],
    ["MIRECS", "MI"],
    ["M_RETS", "MR"],
    ["NAR", "N"],
    ["NC_RETS", "NC"],
    ["NEPOOL_GIS", "NE"],
    ["NVTREK", "NV"],
    ["NYGATS", "NY"],
    ["NONE", "NON"],
  ],
  country: [
    ["US", "united states"]
  ],
  states: [
    ["AL", "AL"],
    ["AK", "AK"],
    ["AS", "AS"],
    ["AZ", "AZ"],
    ["AR", "AR"],
    ["CA", "CA"],
    ["CO", "CT"],
    ["DE", "DE"],
    ["DC", "DC"],
    ["FM", "FM"],
    ["FL", "FL"],
    ["GA", "GA"],
    ["GU", "GU"],
    ["HI", "HI"],
    ["ID", "ID"],
    ["IL", "IL"],
    ["IN", "IN"],
    ["IA", "IA"],
    ["KS", "KS"],
    ["KY", "KY"],
    ["LA", "LA"],
    ["ME", "ME"],
    ["MH", "MH"],
    ["MD", "MD"],
    ["MA", "MA"],
    ["MI", "MI"],
    ["MN", "MN"],
    ["MS", "MS"],
    ["MO", "MO"],
    ["MT", "MT"],
    ["NE", "NE"],
    ["NV", "NV"],
    ["NH", "NH"],
    ["NJ", "NJ"],
    ["NM", "NM"],
    ["NY", "NY"],
    ["NC", "NC"],
    ["ND", "ND"],
    ["MP", "MP"],
    ["OH", "OH"],
    ["OK", "OK"],
    ["OR", "OR"],
    ["PW", "PW"],
    ["PA", "PA"],
    ["PR", "PR"],
    ["RI", "RI"],
    ["SC", "SC"],
    ["SD", "SD"],
    ["TN", "TN"],
    ["TX", "TX"],
    ["UT", "UT"],
    ["VT", "VT"],
    ["VI", "VI"],
    ["VA", "VA"],
    ["WA", "WA"],
    ["WV", "WV"],
    ["WI", "WI"],
    ["WY", "WY"],
  ],
  state: [
    ["AL", "AL"],
    ["AK", "AK"],
    ["AS", "AS"],
    ["AZ", "AZ"],
    ["AR", "AR"],
    ["CA", "CA"],
    ["CO", "CT"],
    ["DE", "DE"],
    ["DC", "DC"],
    ["FM", "FM"],
    ["FL", "FL"],
    ["GA", "GA"],
    ["GU", "GU"],
    ["HI", "HI"],
    ["ID", "ID"],
    ["IL", "IL"],
    ["IN", "IN"],
    ["IA", "IA"],
    ["KS", "KS"],
    ["KY", "KY"],
    ["LA", "LA"],
    ["ME", "ME"],
    ["MH", "MH"],
    ["MD", "MD"],
    ["MA", "MA"],
    ["MI", "MI"],
    ["MN", "MN"],
    ["MS", "MS"],
    ["MO", "MO"],
    ["MT", "MT"],
    ["NE", "NE"],
    ["NV", "NV"],
    ["NH", "NH"],
    ["NJ", "NJ"],
    ["NM", "NM"],
    ["NY", "NY"],
    ["NC", "NC"],
    ["ND", "ND"],
    ["MP", "MP"],
    ["OH", "OH"],
    ["OK", "OK"],
    ["OR", "OR"],
    ["PW", "PW"],
    ["PA", "PA"],
    ["PR", "PR"],
    ["RI", "RI"],
    ["SC", "SC"],
    ["SD", "SD"],
    ["TN", "TN"],
    ["TX", "TX"],
    ["UT", "UT"],
    ["VT", "VT"],
    ["VI", "VI"],
    ["VA", "VA"],
    ["WA", "WA"],
    ["WV", "WV"],
    ["WI", "WI"],
    ["WY", "WY"],
  ],
  side: [
    ["ALL", ""],
    ["BUY", "B"],
    ["SELL", "S"],
  ],
  order_type: [
    ["AUCTION", "A"],
    ["MARKET", "M"]
  ],
  qty: [...Array(10)].map((_, i) => [i + 1, i + 1])
};

export const filter = {
  generator_types: "Generator Type",
  certifying_bodies: "Certifying Body",
  states: "States",
  side: "Order Side",
  qty: "Quantity",
}
export const dashboardMap = {
  generator: [
    "Decomission Date",
    "Place In Service",
    "Ceritifying Body",
    "Nameplate Rating",
    "Type",
    "State",
    "Name",
  ],
  recs: [
    "Generator ID",
    "Quantity",
    "Days to Green-e Expiration",
    "Serial Num Range",
    "Token ID",
    "Vintage Date",
    "Status",
    "Action",
  ],
  orders: [
    "Order Id",
    "Status",
    "Side",
    "QTY",
    "Start Price",
    "Floor Price",
    "Order Expire",
  ],
  transaction: [
    "Generator ID",
    "Price",
    "Quantity",
    "Token ID",
    "Type",
    "Txt Hash",
    "Time Stamp",
  ],
};

export const dashboardUrlMap = {
  transaction: "/order/transaction",
  orders: "/order/search?owner=ME",
  recs: "/rec-token/list/",
  generator: "/generator-asset/",
};
export const dashboardTabMap = {
  generator: [
    ["decomissioned_dt", false],
    ["service_start_dt", false],
    ["certifying_body", true],
    ["nameplate_rating", false],
    ["generator_type", true],
    ["state", false],
    ["generator_name", false],
  ],
  recs: [
    ["id", false],
    ["qty", false],
    ["withdrawn_dt", true],
    ["serial_num_begin", false],
    ["token_id", false],
    ["vintage_dt", false],
    ["status", true],
    ["", false],
  ],
  orders: [
    ["id", false],
    ["status", true],
    ["side", true],
    ["qty", false],
    ["price_start", true],
    ["price_end", true],
    ["end_dt", true],
  ],
  transaction: [
    ["id", false],
    ["price", true],
    ["serial_num_end", false],
    ["serial_num_begin", false],
    ["tx_type", true],
    ["tx_hashes", false],
    ["timestamp", true],
  ]
};

export const orderForm = {
  S: [
      " order_type",
      " qty",
      " price_start",
      " price_end",
      " end_dt_epoch_secs",
      " rec_token",
    ]

    ,
  B: [
    "order_type",
    "qty",
    "price_start",
    "price_end",
    "end_dt_epoch_secs",
    "vintage_dt_min",
    "generator_types",
    "certifying_bodies",
    "states",
  ]
}
