export const generatorMap = {
  generatorType: {
    S: "SOLAR",
    W: "WIND",
    H: "HYDRO",
    G: "GEO",
    BM: "BIOMASS",
    BG: "BIOGAS",
    V: "VAR",
  },
  "certifying_bodies_for_ui": {
    W: "WREGIS",
    P: "PJM",
    E: "ERCOT",
    MI: "MIRECS",
    MR: "M-RETS",
    N: "NAR",
    NC: "NC-RETS",
    NE: "NEPOLL-GI",
    NV: "NVREK",
    NY: "NYGATS",
    NON: "NONE",
  }
};

export const recMap = {
  MRR: "MINT_REVIEW_REQ",
  MR: "MINT_REQ",
  M: "MINTED",
  RRR: "RETIRE_REVIEW_REQ",
  RR: "RETIRE_REQ",
  R: "RETIRED",
  WRR: "WITHDRAW_REVIEW_REQ",
  WR: "WITHDRAW_REQ",
  W: "WITHDRAWN",
  TR: "TRANSFER_REQ",
  T: "TRANSFERRED",
  S: "SUSPENDED",
};
export const orderMap = {
  status: {
    D: "DRAFT",
    SR: "SUBMIT_REQ",
    AC: "ACCEPTED",
    CR: "CANCEL_REQ",
    C: "CANCELLED",
    FR: "FILL_REQ",
    F: "FILLED",
    EX: "EXPIRED"
  },
  type: {
    M: "MINT",
    R: "RETIRE",
    W: "WITHDRAW",
    TR: "TRANSFER",
    TX: "TRADE",
  },
  "order_type": {
    "A": "AUCTION",
    "M": "MARKET"
  },
  side: {
    S: "SELL",
    B: "BUY",
  }
};
export const marketMap = {
  "certifying_bodies_for_ui": {
    W: "WREGIS",
    P: "PJM",
    E: "ERCOT",
    MI: "MIRECS",
    MR: "M-RETS",
    N: "NAR",
    NC: "NC-RETS",
    NE: "NEPOLL-GI",
    NV: "NVREK",
    NY: "NYGATS",
    NON: "NONE",
  },
  "order_type": {
    "A": "AUCTION",
    "M": "MARKET"
  },
}
const title = {
  generatorMap,
  orderMap,
  recMap
}

export const optionsMap = {
  changeGenerator: [],
  changeOwner: [""],
  action: [
    ["Remove", "withdraw"],
    ["Retire", "retire"],
    ["Transfer", "transfer"],
  ],
  alreadyListedGenerator: [],
  generatorType: [
    ["GEOTHERMAL", "G"],
    ["SOLAR", "S"],
    ["WIND", "W"],
    ["HYDRO", "H"],
    ["BIOMASS", "B"],
    ["BIOGAS", "B"],
    ["VARIOUS", "V"],
  ],
  customerClass: [],
  certifyingBody: [
    ["WREGIS", "W"],
    ["PJM_GATS", "P"],
    ["ERCOT", "E"],
    ["MIRECS", "MI"],
    ["M_RETS", "MR"],
    ["NAR", "N"],
    ["NC_RETS", "NC"],
    ["NEPOOL_GIS", "NE"],
    ["NVTREK", "NV"],
    ["NYGATS", "NY"],
    ["NONE", "NON"],
  ],
  country: [
    ["US", "united states"]
  ],
  state: [
    ["AL", "Alabama"],
    ["AK", "Alaska"],
    ["AS", "American Samoa"],
    ["AZ", "Arizona"],
    ["AR", "Arkansas"],
    ["CA", "California"],
    ["CO", "Colorado"],
    ["CT", "Connecticut"],
    ["DE", "Delaware"],
    ["DC", "District Of Columbia"],
    ["FM", "Federated States Of Micronesia"],
    ["FL", "Florida"],
    ["GA", "Georgia"],
    ["GU", "Guam"],
    ["HI", "Hawaii"],
    ["ID", "Idaho"],
    ["IL", "Illinois"],
    ["IN", "Indiana"],
    ["IA", "Iowa"],
    ["KS", "Kansas"],
    ["KY", "Kentucky"],
    ["LA", "Louisiana"],
    ["ME", "Maine"],
    ["MH", "Marshall Islands"],
    ["MD", "Maryland"],
    ["MA", "Massachusetts"],
    ["MI", "Michigan"],
    ["MN", "Minnesota"],
    ["MS", "Mississippi"],
    ["MO", "Missouri"],
    ["MT", "Montana"],
    ["NE", "Nebraska"],
    ["NV", "Nevada"],
    ["NH", "New Hampshire"],
    ["NJ", "New Jersey"],
    ["NM", "New Mexico"],
    ["NY", "New York"],
    ["NC", "North Carolina"],
    ["ND", "North Dakota"],
    ["MP", "Northern Mariana Islands"],
    ["OH", "Ohio"],
    ["OK", "Oklahoma"],
    ["OR", "Oregon"],
    ["PW", "Palau"],
    ["PA", "Pennsylvania"],
    ["PR", "Puerto Rico"],
    ["RI", "Rhode Island"],
    ["SC", "South Carolina"],
    ["SD", "South Dakota"],
    ["TN", "Tennessee"],
    ["TX", "Texas"],
    ["UT", "Utah"],
    ["VT", "Vermont"],
    ["VI", "Virgin Islands"],
    ["VA", "Virginia"],
    ["WA", "Washington"],
    ["WV", "West Virginia"],
    ["WI", "Wisconsin"],
    ["WY", "Wyoming"],
  ],
  side: [
    ["ALL", ""],
    ["BUY", "B"],
    ["SELL", "S"],
  ],
};
